### ISSUE TITLE
Popcornpi drivers with LCDd

### ISSUE THREAD

**Issue by SY-Me** [alidaf/raspberryPi#1]
Hi alidaf,

I need some help from you. I have an old popcorn hour C-200 but this one is crash… I have already a raspberry 2 and i want to place it inside the C-200. I block with the LCD.. I think that i correctly connect the raspberry to the J1 FIP
Rasp: Pin14 (5v) –> J1 FIP: 1
Rasp: Pin16 (GND) –> FIP:2
Rasp: PIN2 (SLA) –> J1 FIP:9
Rasp: PIN3 (SLC) –> J1 FIP:10
It’s correct for you? Have i forgot anything else to connect?

Also, i’m running under OPENELEC. I install LDCproc & I2Ctool. When i running the i2ctool, i see the the I2C port appear (0x5D & 0x6D)
And edit the LCDd.conf with this lines:

---------------------------------------------------------------------------

#Server section with all kinds of settings for the LCDd server 
[server]
DriverPath=/storage/.config/raspdrivers/
Driver=hd44780
Bind=127.0.0.1
Port=13666
User=root
Foreground=yes

#Hello message: each entry represents a display line; default: builtin
Hello=” Welcome to”
Hello=” OpenElec”

#GoodBye message: each entry represents a display line; default: builtin
GoodBye=”Bye bye”
GoodBye=” C U”
#Sets the default time in seconds to displays a screen.
WaitTime=5
#set title scrolling speed [default: 10; legal: 0-10]
TitleSpeed=1
#The menu section. The menu is an internal LCDproc client. ##
[menu]
#Hitachi HD44780 driver ##
[hd44780]
ConnectionType=i2c
#Port where the LPT is. Usual value are: 0x278, 0x378 and 0x3BC
Port=0x5d,0x6d,0x36
#Device of the serial interface [default: /dev/lcd]
Device=/dev/i2c-1
#Bitrate of the serial port (0 for interface default)
Speed=0
#Specifies the size of the LCD.
#In case of multiple combined displays, this should be the total size.
Size=16×2
CharMap=hd44780_default
DelayMult=4

---------------------------------------------------------------------------

So, my big problem it’s that the display show me nothing… I try with your drivers but nothing too. Can you help me please?? My connection are correct? The LCDd.conf are correct too?
Thx a lot guy, and i hope that you can help me cause even in google i don’t find anything… :-(

**Comment by alidaf** [comment]
I'm not too familiar with LCDProc but I don't think it will work as I think it is only for LCD text displays.  The AMG19264 is a graphic display so it doesn't have any fonts built in. I think a framebuffer driver is what you actually need. The only open-source project for framebuffer drivers that I know of is notro/fbtft but that is not accepting any new code.

Unfortunately, I abandoned the driver project because I destroyed the display when I tried to get it out and solder some headers to it. I never figured out what some of the jumpers did and wrote that as a template to build on.

Sorry I couldn't help but don't give up. The case and display will make a great RPi media centre far better than the crap that came with it! Good luck.
