### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Soulace1970** [alidaf/raspberryPi#3]
Hi Darren - I have  PCH-C200 which I would like to install a Pi 3. How did you get on with this project?

Regards,
Alex
Australia

**Comment by alidaf** [comment]
Not very well I'm afraid. I completely destroyed the display trying to unsolder all of the pins.

**Comment by Soulace1970** [comment]
Can the manufacturer be contacted for a bare bones display?

**Comment by Soulace1970** [comment]
Was it something like this? http://www.buydisplay.com/default/3-3-inch-display-192x64-19264-lcd-monochrome-module-white-on-blue

**Comment by alidaf** [comment]
It is the same model. The C200 has a bigger board that the display solders onto but I've since thrown all the bits away, including the case. From what I remember, the interface is very similar to the HD44780 but with graphics. I don't think it would be too difficult to program but the hard part is providing the API primitives to do things like draw shapes and text.
The driver itself, which is what I started to write would have provided the very basic hardware functions and not a graphical API. I started on an SSD1322, which is a smaller OLED board for another project and fell down at that hurdle and I moved onto some Arduino projects. I'm pretty sure that there is a generic driver for LCD displays that may work. I can't remember what it was but have a look at this https://lcd4linux.bulix.org/ 
I wish I'd kept hold of everything now. I should probably remove all the incomplete code too.

**Comment by Soulace1970** [comment]
Hi Darren, Thanks for that. Pity you threw that such good looking case away! Oh well perhaps another one may turn up somehwere!

**Comment by Soulace1970** [comment]
Do you have any idea what to do with the front fascia controls next to the LCD?

**Comment by alidaf** [comment]
When I first started I used this site to determine what the different components were...https://hardwarebug.org/2015/02/26/popcorn-hour-revisited/
You may find it useful. It looks like J1 is where the buttons are passed through. The site has a list of what the pins relate to but I think the buttons are processed by an unmarked microcontroller on the board.

**Comment by alidaf** [comment]
I'm closing this issue. Open it again if you need anything else.
